# Generated by Django 3.1.2 on 2020-11-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20201105_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePersons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('edad', models.IntegerField()),
                ('correo', models.CharField(max_length=255)),
            ],
        ),
    ]
